#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: da8b975
#
Name     : ipset
Version  : 7.21
Release  : 40
URL      : https://www.netfilter.org/pub/ipset/ipset-7.21.tar.bz2
Source0  : https://www.netfilter.org/pub/ipset/ipset-7.21.tar.bz2
Source1  : ipset.service
Summary  : Userspace library for the ipset extensions and the kernel interface
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: ipset-bin = %{version}-%{release}
Requires: ipset-lib = %{version}-%{release}
Requires: ipset-license = %{version}-%{release}
Requires: ipset-man = %{version}-%{release}
Requires: ipset-services = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : grep
BuildRequires : pkgconfig(libmnl)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the ipset source tree. Follow the next steps to install ipset.
If you upgrade from an earlier 5.x release, please read the UPGRADE
instructions too.

%package bin
Summary: bin components for the ipset package.
Group: Binaries
Requires: ipset-license = %{version}-%{release}
Requires: ipset-services = %{version}-%{release}

%description bin
bin components for the ipset package.


%package dev
Summary: dev components for the ipset package.
Group: Development
Requires: ipset-lib = %{version}-%{release}
Requires: ipset-bin = %{version}-%{release}
Provides: ipset-devel = %{version}-%{release}
Requires: ipset = %{version}-%{release}

%description dev
dev components for the ipset package.


%package lib
Summary: lib components for the ipset package.
Group: Libraries
Requires: ipset-license = %{version}-%{release}

%description lib
lib components for the ipset package.


%package license
Summary: license components for the ipset package.
Group: Default

%description license
license components for the ipset package.


%package man
Summary: man components for the ipset package.
Group: Default

%description man
man components for the ipset package.


%package services
Summary: services components for the ipset package.
Group: Systemd services
Requires: systemd

%description services
services components for the ipset package.


%prep
%setup -q -n ipset-7.21
cd %{_builddir}/ipset-7.21
pushd ..
cp -a ipset-7.21 buildavx2
popd
pushd ..
cp -a ipset-7.21 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707754815
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-kmod=no \
--enable-bashcompl
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-kmod=no \
--enable-bashcompl
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildapx/
GOAMD64=v3
CC="gcc-14"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --host=x86_64-clr-linux-gnu --disable-static --with-kmod=no \
--enable-bashcompl
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707754815
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipset
cp %{_builddir}/ipset-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ipset/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
cp %{_builddir}/ipset-%{version}/libltdl/COPYING.LIB %{buildroot}/usr/share/package-licenses/ipset/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v3
pushd ../buildapx/
%make_install_va
popd
GOAMD64=v2
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/ipset.service
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ipset
/usr/bin/ipset
/usr/bin/ipset-translate

%files dev
%defattr(-,root,root,-)
/usr/include/libipset/args.h
/usr/include/libipset/data.h
/usr/include/libipset/errcode.h
/usr/include/libipset/ipset.h
/usr/include/libipset/linux_ip_set.h
/usr/include/libipset/linux_ip_set_bitmap.h
/usr/include/libipset/linux_ip_set_hash.h
/usr/include/libipset/linux_ip_set_list.h
/usr/include/libipset/mnl.h
/usr/include/libipset/nf_inet_addr.h
/usr/include/libipset/nfproto.h
/usr/include/libipset/parse.h
/usr/include/libipset/pfxlen.h
/usr/include/libipset/print.h
/usr/include/libipset/session.h
/usr/include/libipset/transport.h
/usr/include/libipset/types.h
/usr/include/libipset/utils.h
/usr/include/libipset/xlate.h
/usr/lib64/libipset.so
/usr/lib64/pkgconfig/libipset.pc
/usr/share/man/man3/libipset.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libipset.so.13.4.0
/usr/lib64/libipset.so.13
/usr/lib64/libipset.so.13.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipset/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/ipset/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/ipset-translate.8
/usr/share/man/man8/ipset.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/ipset.service
